project:
  type: website

website:
  title: GrasWurzelGrün
  favicon: images/grass_2.jpg
  navbar:
    logo: images/grass_2.jpg
    left:
      - href: index.qmd
        text: Start
      - news.qmd
  cookie-consent:
    type: express
  page-footer: "[Impressum](/impressum.qmd) - [Datenschutzerklärung](/datenschutzerklaerung.qmd)"
  twitter-card: true
  open-graph: true
  image: images/grass_2.jpg
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



